lib/github_events_web/router.ex
defmodule GithubEventsWeb.Router do
  use GithubEventsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {GithubEventsWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug GithubEventsWeb.Auth
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :authorize do
    plug GithubEventsWeb.Authorize
  end

  scope "/", GithubEventsWeb do
    pipe_through :browser

    get "/", PageController, :index

    pipe_through :authorize
    live "/github_events", EventLive
    live "/profile", ProfileLive
  end

  scope "/auth", GithubEventsWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
    delete "/logout", AuthController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", GithubEventsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: GithubEventsWeb.Telemetry
    end
  end
end

lib/github_events_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1>Login to proceed</h1>
  <%= if @current_user do %>
    <h2>Welcome, <%= @current_user.owner %>!</h2>
    <div>
      <img src="<%= @current_user.avatar %>" />
    </div>
    <%= link "Logout", to: Routes.auth_path(@conn, :delete), method: "delete", class: "button" %>
    <%= link "Profile", to: Routes.live_path(GithubEventsWeb.Endpoint, GithubEventsWeb.ProfileLive), class: "button" %>
    <br>
  <% else %>
    <ul style="list-style: none">
      <li>
        <a class="button" href="<%= Routes.auth_path(@conn, :request, "github") %>">
          <i class="fa fa-github"></i>
          Sign in with GitHub
        </a>
      </li>
    </ul>
  <% end %>
</section>